### ISSUE TITLE
Special characters may break passwords

### ISSUE THREAD

**Issue by slarti5191** [slarti5191/splendid#5]
Needs more investigation, password seems to end before '#' character in debug output.

**Comment by slarti5191** [comment]
https://github.com/go-ini/ini#comment

Documentation is the key.

**Comment by dustingraham** [comment]
Does this mean it is working for you if you put `Pass="some#pass"` ?

**Comment by slarti5191** [comment]
"" did not work, but Pass=\`some#pass\` does work.

**Comment by dustingraham** [comment]
We can either mention it in the documentation such as https://github.com/slarti5191/splendid/commit/5ebb22443a9637f48a44df84c471f99b7fd49614

Or, we could try using the IgnoreInlineComment flag, which might be feasible.
